export default function serializeDynamicObject({
  acceleration,
  affectedByGravity,
  angle,
  bending,
  bendingAngle,
  bendingIncrements,
  components,
  deceleration,
  friction,
  height,
  id,
  isAccelerating,
  isRotatingLeft,
  isRotatingRight,
  playerId,
  position,
  rotationSpeed,
  velocity,
  width,
  bendingMultiple,
  bendingVelocityMultiple,
  maxSpeed
}) {
  const obj = {
    acceleration,
    affectedByGravity,
    angle,
    bending: { ...bending, __typename: "TwoVector" },
    bendingAngle,
    bendingIncrements,
    deceleration,
    friction: { ...friction, __typename: "TwoVector" },
    height,
    id,
    isAccelerating,
    isRotatingLeft,
    isRotatingRight,
    playerId,
    position: { ...position, __typename: "TwoVector" },
    rotationSpeed,
    velocity: { ...velocity, __typename: "TwoVector" },
    width,
    bendingMultiple,
    bendingVelocityMultiple,
    maxSpeed,
    __typename: "DynamicObject"
  };
  return obj;
}
